
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'one_bite_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  run_start: '1994-06-22' #Placeholder, value will always be passed in through airflow run config
  run_end: '1994-06-22' #Placeholder, value will always be passed in through airflow run config

models:
    one_bite_dbt:
        staging:
            materialized: incremental
        analytics:
            materialized: incremental
            tags: sheets #Will be sent to Google Sheets for tableau usage
        
seeds: 
    stage_regions:
        enabled: True
        quotes_columns: False